import type { ObjectDef } from "@/engine/metadata"

import {
  DOCUMENT_CATEGORIES,
  DOCUMENT_CATEGORY_LABELS,
  INCOTERM_OPTIONS,
  MILESTONE_OPTIONS,
  option,
  QUOTE_STATUS_COLORS,
  QUOTE_STATUS_LABELS,
  QUOTE_STATUSES,
  t,
  TRANSPORT_MODE_OPTIONS,
} from "../lib/constants"
import {
  CURRENCY_OPTIONS,
  newestFirst,
  relation,
  SYSTEM_SECTION,
  systemFields,
} from "./shared"

const SEA_MODES = ["SEA_FCL", "SEA_LCL", "MULTIMODAL"]

/**
 * Quote header (B3.4). Charges, options and revisions live behind the
 * quote API; the header is kept in sync by the server, so business fields
 * are read-only here and edited in the quote builder.
 */
export function quoteObject(): ObjectDef {
  return {
    key: "quote",
    label: t("Teklif", "Quote"),
    pluralLabel: t("Teklifler", "Quotes"),
    icon: "receipt",
    primaryField: "quoteNumber",
    searchFields: ["quoteNumber", "carrier"],
    createPath: "/quotes/new",
    fields: [
      {
        key: "quoteNumber",
        label: t("Teklif no", "Quote no"),
        type: "text",
        system: true,
        readOnly: true,
      },
      {
        key: "status",
        label: t("Durum", "Status"),
        type: "select",
        system: true,
        readOnly: true,
        options: QUOTE_STATUSES.map((status) =>
          option(
            status,
            QUOTE_STATUS_LABELS[status],
            QUOTE_STATUS_COLORS[status]
          )
        ),
      },
      {
        key: "version",
        label: t("Versiyon", "Version"),
        type: "number",
        system: true,
        readOnly: true,
      },
      {
        key: "companyId",
        label: t("Müşteri", "Customer"),
        type: "relation",
        relation: relation("company"),
        system: true,
        readOnly: true,
      },
      {
        key: "contactId",
        label: t("Kişi", "Contact"),
        type: "relation",
        relation: relation("contact"),
        system: true,
        readOnly: true,
      },
      {
        key: "dealId",
        label: t("Fırsat", "Deal"),
        type: "relation",
        relation: relation("deal"),
        system: true,
        readOnly: true,
      },
      {
        key: "leadId",
        label: t("Navlun talebi", "Freight request"),
        type: "relation",
        relation: relation("lead"),
        system: true,
        readOnly: true,
      },
      {
        key: "transportMode",
        label: t("Taşıma modu", "Transport mode"),
        type: "select",
        options: TRANSPORT_MODE_OPTIONS,
        system: true,
        readOnly: true,
      },
      {
        key: "origin",
        label: t("Çıkış", "Origin"),
        type: "location",
        system: true,
        readOnly: true,
      },
      {
        key: "destination",
        label: t("Varış", "Destination"),
        type: "location",
        system: true,
        readOnly: true,
      },
      {
        key: "incoterm",
        label: t("Incoterm", "Incoterm"),
        type: "select",
        options: INCOTERM_OPTIONS,
        system: true,
        readOnly: true,
      },
      {
        key: "currency",
        label: t("Teklif para birimi", "Quote currency"),
        type: "select",
        options: CURRENCY_OPTIONS,
        system: true,
        readOnly: true,
      },
      {
        key: "validUntil",
        label: t("Geçerlilik", "Valid until"),
        type: "date",
        system: true,
        readOnly: true,
      },
      {
        key: "carrier",
        label: t("Taşıyıcı", "Carrier"),
        type: "text",
        system: true,
        readOnly: true,
      },
      {
        key: "transitDays",
        label: t("Transit süre (gün)", "Transit (days)"),
        type: "number",
        system: true,
        readOnly: true,
      },
      {
        key: "totalSell",
        label: t("Satış toplamı", "Total (sell)"),
        type: "currency",
        system: true,
        readOnly: true,
      },
      {
        key: "totalBuy",
        label: t("Alış toplamı", "Total (buy)"),
        type: "currency",
        system: true,
        readOnly: true,
      },
      {
        key: "marginPercent",
        label: t("Kâr marjı", "Margin"),
        type: "percent",
        system: true,
        readOnly: true,
      },
      {
        key: "sentAt",
        label: t("Gönderilme", "Sent"),
        type: "datetime",
        system: true,
        readOnly: true,
      },
      {
        key: "shipmentId",
        label: t("Sevkiyat", "Shipment"),
        type: "relation",
        relation: relation("shipment", "shipmentNumber"),
        system: true,
        readOnly: true,
      },
      {
        key: "notes",
        label: t("İç notlar", "Internal notes"),
        type: "textarea",
      },
      ...systemFields(),
    ],
    layouts: {
      list: {
        columns: [
          "quoteNumber",
          "companyId",
          "status",
          "transportMode",
          "origin",
          "destination",
          "totalSell",
          "marginPercent",
          "validUntil",
          "ownerId",
        ],
        defaultSort: newestFirst,
      },
      detail: {
        highlights: ["status", "totalSell", "marginPercent", "validUntil"],
        sections: [
          {
            key: "overview",
            label: t("Teklif", "Quote"),
            fields: [
              "quoteNumber",
              "version",
              "status",
              "companyId",
              "contactId",
              "dealId",
              "leadId",
              "validUntil",
              "sentAt",
              "shipmentId",
            ],
          },
          {
            key: "route",
            label: t("Rota & taşıyıcı", "Route & carrier"),
            fields: [
              "transportMode",
              "origin",
              "destination",
              "incoterm",
              "carrier",
              "transitDays",
            ],
          },
          {
            key: "totals",
            label: t("Tutarlar", "Totals"),
            fields: ["currency", "totalSell", "totalBuy", "marginPercent"],
          },
          SYSTEM_SECTION,
          { key: "notes", label: t("Notlar", "Notes"), fields: ["notes"] },
        ],
        related: [],
      },
    },
  }
}

/** Booking / shipment (B3.5). Status and actual dates follow milestones. */
export function shipmentObject(): ObjectDef {
  return {
    key: "shipment",
    label: t("Sevkiyat", "Shipment"),
    pluralLabel: t("Sevkiyatlar", "Shipments"),
    icon: "container",
    primaryField: "shipmentNumber",
    searchFields: ["shipmentNumber", "bookingRef", "blNumber", "awbNumber"],
    fileCategories: DOCUMENT_CATEGORIES.map((category) =>
      option(category, DOCUMENT_CATEGORY_LABELS[category], "blue")
    ),
    fields: [
      {
        key: "shipmentNumber",
        label: t("Sevkiyat no", "Shipment no"),
        type: "text",
        system: true,
        readOnly: true,
      },
      {
        key: "status",
        label: t("Durum", "Status"),
        type: "select",
        system: true,
        readOnly: true,
        options: MILESTONE_OPTIONS,
      },
      {
        key: "delayed",
        label: t("Gecikmede", "Delayed"),
        type: "boolean",
        system: true,
        readOnly: true,
      },
      {
        key: "mode",
        label: t("Taşıma modu", "Transport mode"),
        type: "select",
        required: true,
        system: true,
        options: TRANSPORT_MODE_OPTIONS,
      },
      {
        key: "origin",
        label: t("Çıkış", "Origin"),
        type: "location",
        required: true,
        system: true,
      },
      {
        key: "destination",
        label: t("Varış", "Destination"),
        type: "location",
        required: true,
        system: true,
      },
      {
        key: "etd",
        label: t("ETD (planlanan çıkış)", "ETD"),
        type: "date",
        system: true,
      },
      {
        key: "eta",
        label: t("ETA (planlanan varış)", "ETA"),
        type: "date",
        system: true,
      },
      {
        key: "atd",
        label: t("ATD (gerçekleşen çıkış)", "ATD"),
        type: "date",
        system: true,
        readOnly: true,
      },
      {
        key: "ata",
        label: t("ATA (gerçekleşen varış)", "ATA"),
        type: "date",
        system: true,
        readOnly: true,
      },
      {
        key: "customerId",
        label: t("Müşteri", "Customer"),
        type: "relation",
        relation: relation("company"),
        required: true,
        system: true,
      },
      {
        key: "shipperId",
        label: t("Gönderici (shipper)", "Shipper"),
        type: "relation",
        relation: relation("company"),
      },
      {
        key: "consigneeId",
        label: t("Alıcı (consignee)", "Consignee"),
        type: "relation",
        relation: relation("company"),
      },
      {
        key: "notifyPartyId",
        label: t("İhbar tarafı (notify)", "Notify party"),
        type: "relation",
        relation: relation("company"),
      },
      {
        key: "agentId",
        label: t("Acente", "Agent"),
        type: "relation",
        relation: relation("company"),
      },
      { key: "carrier", label: t("Taşıyıcı", "Carrier"), type: "text" },
      {
        key: "bookingRef",
        label: t("Booking no", "Booking ref"),
        type: "text",
      },
      {
        key: "blNumber",
        label: t("Konşimento (B/L) no", "B/L number"),
        type: "text",
        visibleWhen: [{ field: "mode", op: "in", value: SEA_MODES }],
      },
      {
        key: "awbNumber",
        label: t("AWB no", "AWB number"),
        type: "text",
        visibleWhen: [{ field: "mode", op: "in", value: ["AIR"] }],
      },
      {
        key: "containers",
        label: t("Konteynerler", "Containers"),
        type: "container",
        visibleWhen: [{ field: "mode", op: "in", value: ["SEA_FCL"] }],
      },
      { key: "commodity", label: t("Emtia", "Commodity"), type: "text" },
      {
        key: "packageCount",
        label: t("Kap adedi", "Packages"),
        type: "number",
        validation: { min: 0 },
      },
      {
        key: "grossWeight",
        label: t("Brüt ağırlık", "Gross weight"),
        type: "weight",
        validation: { min: 0 },
      },
      {
        key: "volume",
        label: t("Hacim", "Volume"),
        type: "volume",
        validation: { min: 0 },
      },
      {
        key: "quoteId",
        label: t("Teklif", "Quote"),
        type: "relation",
        relation: relation("quote", "quoteNumber"),
        system: true,
        readOnly: true,
      },
      {
        key: "dealId",
        label: t("Fırsat", "Deal"),
        type: "relation",
        relation: relation("deal"),
      },
      ...systemFields(),
    ],
    layouts: {
      list: {
        columns: [
          "shipmentNumber",
          "customerId",
          "mode",
          "origin",
          "destination",
          "etd",
          "eta",
          "status",
          "delayed",
        ],
        defaultSort: { field: "etd", direction: "desc" },
      },
      detail: {
        highlights: ["status", "mode", "etd", "eta"],
        sections: [
          {
            key: "route",
            label: t("Rota & program", "Route & schedule"),
            fields: [
              "shipmentNumber",
              "mode",
              "origin",
              "destination",
              "etd",
              "eta",
              "atd",
              "ata",
              "carrier",
              "bookingRef",
              "blNumber",
              "awbNumber",
            ],
          },
          {
            key: "parties",
            label: t("Taraflar", "Parties"),
            fields: [
              "customerId",
              "shipperId",
              "consigneeId",
              "notifyPartyId",
              "agentId",
            ],
          },
          {
            key: "cargo",
            label: t("Yük", "Cargo"),
            fields: [
              "commodity",
              "containers",
              "packageCount",
              "grossWeight",
              "volume",
            ],
          },
          {
            key: "links",
            label: t("Bağlantılar", "Links"),
            fields: ["quoteId", "dealId"],
          },
          SYSTEM_SECTION,
        ],
        related: [],
      },
    },
  }
}
