/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppExamplesRouteImport } from './routes/_app/examples'
import { Route as AppFormsRouteImport } from './routes/_app/forms'
import { Route as AppQuotesRouteImport } from './routes/_app/quotes'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppFormsIndexRouteImport } from './routes/_app/forms/index'
import { Route as AppFormsFormIdRouteImport } from './routes/_app/forms/$formId'
import { Route as AppOObjectKeyRouteImport } from './routes/_app/o/$objectKey'
import { Route as AppQuotesIndexRouteImport } from './routes/_app/quotes/index'
import { Route as AppQuotesQuoteIdRouteImport } from './routes/_app/quotes/$quoteId'
import { Route as AppQuotesNewRouteImport } from './routes/_app/quotes/new'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsMembersRouteImport } from './routes/_app/settings/members'
import { Route as AppSettingsObjectsRouteImport } from './routes/_app/settings/objects'
import { Route as AppFormsFormIdIndexRouteImport } from './routes/_app/forms/$formId/index'
import { Route as AppFormsFormIdEditRouteImport } from './routes/_app/forms/$formId/edit'
import { Route as AppOObjectKeyIndexRouteImport } from './routes/_app/o/$objectKey/index'
import { Route as AppOObjectKeyRecordIdRouteImport } from './routes/_app/o/$objectKey/$recordId'
import { Route as AppOObjectKeyNewRouteImport } from './routes/_app/o/$objectKey/new'
import { Route as AppQuotesQuoteIdIndexRouteImport } from './routes/_app/quotes/$quoteId/index'
import { Route as AppQuotesQuoteIdPrintRouteImport } from './routes/_app/quotes/$quoteId/print'
import { Route as AppSettingsObjectsIndexRouteImport } from './routes/_app/settings/objects/index'
import { Route as AppSettingsObjectsObjectKeyRouteImport } from './routes/_app/settings/objects/$objectKey'
import { Route as AppOObjectKeyRecordIdIndexRouteImport } from './routes/_app/o/$objectKey/$recordId/index'
import { Route as AppOObjectKeyRecordIdEditRouteImport } from './routes/_app/o/$objectKey/$recordId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppExamplesRoute = AppExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesRoute = AppQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppFormsIndexRoute = AppFormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFormsRoute,
} as any)
const AppFormsFormIdRoute = AppFormsFormIdRouteImport.update({
  id: '/$formId',
  path: '/$formId',
  getParentRoute: () => AppFormsRoute,
} as any)
const AppOObjectKeyRoute = AppOObjectKeyRouteImport.update({
  id: '/o/$objectKey',
  path: '/o/$objectKey',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQuotesRoute,
} as any)
const AppQuotesQuoteIdRoute = AppQuotesQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => AppQuotesRoute,
} as any)
const AppQuotesNewRoute = AppQuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppQuotesRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsObjectsRoute = AppSettingsObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppFormsFormIdIndexRoute = AppFormsFormIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFormsFormIdRoute,
} as any)
const AppFormsFormIdEditRoute = AppFormsFormIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppFormsFormIdRoute,
} as any)
const AppOObjectKeyIndexRoute = AppOObjectKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOObjectKeyRoute,
} as any)
const AppOObjectKeyRecordIdRoute = AppOObjectKeyRecordIdRouteImport.update({
  id: '/$recordId',
  path: '/$recordId',
  getParentRoute: () => AppOObjectKeyRoute,
} as any)
const AppOObjectKeyNewRoute = AppOObjectKeyNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppOObjectKeyRoute,
} as any)
const AppQuotesQuoteIdIndexRoute = AppQuotesQuoteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQuotesQuoteIdRoute,
} as any)
const AppQuotesQuoteIdPrintRoute = AppQuotesQuoteIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => AppQuotesQuoteIdRoute,
} as any)
const AppSettingsObjectsIndexRoute = AppSettingsObjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsObjectsRoute,
} as any)
const AppSettingsObjectsObjectKeyRoute =
  AppSettingsObjectsObjectKeyRouteImport.update({
    id: '/$objectKey',
    path: '/$objectKey',
    getParentRoute: () => AppSettingsObjectsRoute,
  } as any)
const AppOObjectKeyRecordIdIndexRoute =
  AppOObjectKeyRecordIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOObjectKeyRecordIdRoute,
  } as any)
const AppOObjectKeyRecordIdEditRoute =
  AppOObjectKeyRecordIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppOObjectKeyRecordIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/examples': typeof AppExamplesRoute
  '/forms': typeof AppFormsRouteWithChildren
  '/quotes': typeof AppQuotesRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/tasks': typeof AppTasksRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/forms/$formId': typeof AppFormsFormIdRouteWithChildren
  '/o/$objectKey': typeof AppOObjectKeyRouteWithChildren
  '/quotes/$quoteId': typeof AppQuotesQuoteIdRouteWithChildren
  '/quotes/new': typeof AppQuotesNewRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/objects': typeof AppSettingsObjectsRouteWithChildren
  '/forms/': typeof AppFormsIndexRoute
  '/quotes/': typeof AppQuotesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/forms/$formId/edit': typeof AppFormsFormIdEditRoute
  '/o/$objectKey/$recordId': typeof AppOObjectKeyRecordIdRouteWithChildren
  '/o/$objectKey/new': typeof AppOObjectKeyNewRoute
  '/quotes/$quoteId/print': typeof AppQuotesQuoteIdPrintRoute
  '/settings/objects/$objectKey': typeof AppSettingsObjectsObjectKeyRoute
  '/forms/$formId/': typeof AppFormsFormIdIndexRoute
  '/o/$objectKey/': typeof AppOObjectKeyIndexRoute
  '/quotes/$quoteId/': typeof AppQuotesQuoteIdIndexRoute
  '/settings/objects/': typeof AppSettingsObjectsIndexRoute
  '/o/$objectKey/$recordId/edit': typeof AppOObjectKeyRecordIdEditRoute
  '/o/$objectKey/$recordId/': typeof AppOObjectKeyRecordIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/examples': typeof AppExamplesRoute
  '/tasks': typeof AppTasksRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/quotes/new': typeof AppQuotesNewRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/forms': typeof AppFormsIndexRoute
  '/quotes': typeof AppQuotesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/forms/$formId/edit': typeof AppFormsFormIdEditRoute
  '/o/$objectKey/new': typeof AppOObjectKeyNewRoute
  '/quotes/$quoteId/print': typeof AppQuotesQuoteIdPrintRoute
  '/settings/objects/$objectKey': typeof AppSettingsObjectsObjectKeyRoute
  '/forms/$formId': typeof AppFormsFormIdIndexRoute
  '/o/$objectKey': typeof AppOObjectKeyIndexRoute
  '/quotes/$quoteId': typeof AppQuotesQuoteIdIndexRoute
  '/settings/objects': typeof AppSettingsObjectsIndexRoute
  '/o/$objectKey/$recordId/edit': typeof AppOObjectKeyRecordIdEditRoute
  '/o/$objectKey/$recordId': typeof AppOObjectKeyRecordIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/examples': typeof AppExamplesRoute
  '/_app/forms': typeof AppFormsRouteWithChildren
  '/_app/quotes': typeof AppQuotesRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/tasks': typeof AppTasksRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/forms/$formId': typeof AppFormsFormIdRouteWithChildren
  '/_app/o/$objectKey': typeof AppOObjectKeyRouteWithChildren
  '/_app/quotes/$quoteId': typeof AppQuotesQuoteIdRouteWithChildren
  '/_app/quotes/new': typeof AppQuotesNewRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/settings/objects': typeof AppSettingsObjectsRouteWithChildren
  '/_app/forms/': typeof AppFormsIndexRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/forms/$formId/edit': typeof AppFormsFormIdEditRoute
  '/_app/o/$objectKey/$recordId': typeof AppOObjectKeyRecordIdRouteWithChildren
  '/_app/o/$objectKey/new': typeof AppOObjectKeyNewRoute
  '/_app/quotes/$quoteId/print': typeof AppQuotesQuoteIdPrintRoute
  '/_app/settings/objects/$objectKey': typeof AppSettingsObjectsObjectKeyRoute
  '/_app/forms/$formId/': typeof AppFormsFormIdIndexRoute
  '/_app/o/$objectKey/': typeof AppOObjectKeyIndexRoute
  '/_app/quotes/$quoteId/': typeof AppQuotesQuoteIdIndexRoute
  '/_app/settings/objects/': typeof AppSettingsObjectsIndexRoute
  '/_app/o/$objectKey/$recordId/edit': typeof AppOObjectKeyRecordIdEditRoute
  '/_app/o/$objectKey/$recordId/': typeof AppOObjectKeyRecordIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/examples'
    | '/forms'
    | '/quotes'
    | '/settings'
    | '/tasks'
    | '/forgot-password'
    | '/login'
    | '/forms/$formId'
    | '/o/$objectKey'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/settings/members'
    | '/settings/objects'
    | '/forms/'
    | '/quotes/'
    | '/settings/'
    | '/forms/$formId/edit'
    | '/o/$objectKey/$recordId'
    | '/o/$objectKey/new'
    | '/quotes/$quoteId/print'
    | '/settings/objects/$objectKey'
    | '/forms/$formId/'
    | '/o/$objectKey/'
    | '/quotes/$quoteId/'
    | '/settings/objects/'
    | '/o/$objectKey/$recordId/edit'
    | '/o/$objectKey/$recordId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/examples'
    | '/tasks'
    | '/forgot-password'
    | '/login'
    | '/quotes/new'
    | '/settings/members'
    | '/forms'
    | '/quotes'
    | '/settings'
    | '/forms/$formId/edit'
    | '/o/$objectKey/new'
    | '/quotes/$quoteId/print'
    | '/settings/objects/$objectKey'
    | '/forms/$formId'
    | '/o/$objectKey'
    | '/quotes/$quoteId'
    | '/settings/objects'
    | '/o/$objectKey/$recordId/edit'
    | '/o/$objectKey/$recordId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/onboarding'
    | '/_app/dashboard'
    | '/_app/examples'
    | '/_app/forms'
    | '/_app/quotes'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_app/forms/$formId'
    | '/_app/o/$objectKey'
    | '/_app/quotes/$quoteId'
    | '/_app/quotes/new'
    | '/_app/settings/members'
    | '/_app/settings/objects'
    | '/_app/forms/'
    | '/_app/quotes/'
    | '/_app/settings/'
    | '/_app/forms/$formId/edit'
    | '/_app/o/$objectKey/$recordId'
    | '/_app/o/$objectKey/new'
    | '/_app/quotes/$quoteId/print'
    | '/_app/settings/objects/$objectKey'
    | '/_app/forms/$formId/'
    | '/_app/o/$objectKey/'
    | '/_app/quotes/$quoteId/'
    | '/_app/settings/objects/'
    | '/_app/o/$objectKey/$recordId/edit'
    | '/_app/o/$objectKey/$recordId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/examples': {
      id: '/_app/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof AppExamplesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms': {
      id: '/_app/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes': {
      id: '/_app/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AppQuotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/forms/': {
      id: '/_app/forms/'
      path: '/'
      fullPath: '/forms/'
      preLoaderRoute: typeof AppFormsIndexRouteImport
      parentRoute: typeof AppFormsRoute
    }
    '/_app/forms/$formId': {
      id: '/_app/forms/$formId'
      path: '/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof AppFormsFormIdRouteImport
      parentRoute: typeof AppFormsRoute
    }
    '/_app/o/$objectKey': {
      id: '/_app/o/$objectKey'
      path: '/o/$objectKey'
      fullPath: '/o/$objectKey'
      preLoaderRoute: typeof AppOObjectKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppQuotesRoute
    }
    '/_app/quotes/$quoteId': {
      id: '/_app/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof AppQuotesQuoteIdRouteImport
      parentRoute: typeof AppQuotesRoute
    }
    '/_app/quotes/new': {
      id: '/_app/quotes/new'
      path: '/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AppQuotesNewRouteImport
      parentRoute: typeof AppQuotesRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/objects': {
      id: '/_app/settings/objects'
      path: '/objects'
      fullPath: '/settings/objects'
      preLoaderRoute: typeof AppSettingsObjectsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/forms/$formId/': {
      id: '/_app/forms/$formId/'
      path: '/'
      fullPath: '/forms/$formId/'
      preLoaderRoute: typeof AppFormsFormIdIndexRouteImport
      parentRoute: typeof AppFormsFormIdRoute
    }
    '/_app/forms/$formId/edit': {
      id: '/_app/forms/$formId/edit'
      path: '/edit'
      fullPath: '/forms/$formId/edit'
      preLoaderRoute: typeof AppFormsFormIdEditRouteImport
      parentRoute: typeof AppFormsFormIdRoute
    }
    '/_app/o/$objectKey/': {
      id: '/_app/o/$objectKey/'
      path: '/'
      fullPath: '/o/$objectKey/'
      preLoaderRoute: typeof AppOObjectKeyIndexRouteImport
      parentRoute: typeof AppOObjectKeyRoute
    }
    '/_app/o/$objectKey/$recordId': {
      id: '/_app/o/$objectKey/$recordId'
      path: '/$recordId'
      fullPath: '/o/$objectKey/$recordId'
      preLoaderRoute: typeof AppOObjectKeyRecordIdRouteImport
      parentRoute: typeof AppOObjectKeyRoute
    }
    '/_app/o/$objectKey/new': {
      id: '/_app/o/$objectKey/new'
      path: '/new'
      fullPath: '/o/$objectKey/new'
      preLoaderRoute: typeof AppOObjectKeyNewRouteImport
      parentRoute: typeof AppOObjectKeyRoute
    }
    '/_app/quotes/$quoteId/': {
      id: '/_app/quotes/$quoteId/'
      path: '/'
      fullPath: '/quotes/$quoteId/'
      preLoaderRoute: typeof AppQuotesQuoteIdIndexRouteImport
      parentRoute: typeof AppQuotesQuoteIdRoute
    }
    '/_app/quotes/$quoteId/print': {
      id: '/_app/quotes/$quoteId/print'
      path: '/print'
      fullPath: '/quotes/$quoteId/print'
      preLoaderRoute: typeof AppQuotesQuoteIdPrintRouteImport
      parentRoute: typeof AppQuotesQuoteIdRoute
    }
    '/_app/settings/objects/': {
      id: '/_app/settings/objects/'
      path: '/'
      fullPath: '/settings/objects/'
      preLoaderRoute: typeof AppSettingsObjectsIndexRouteImport
      parentRoute: typeof AppSettingsObjectsRoute
    }
    '/_app/settings/objects/$objectKey': {
      id: '/_app/settings/objects/$objectKey'
      path: '/$objectKey'
      fullPath: '/settings/objects/$objectKey'
      preLoaderRoute: typeof AppSettingsObjectsObjectKeyRouteImport
      parentRoute: typeof AppSettingsObjectsRoute
    }
    '/_app/o/$objectKey/$recordId/': {
      id: '/_app/o/$objectKey/$recordId/'
      path: '/'
      fullPath: '/o/$objectKey/$recordId/'
      preLoaderRoute: typeof AppOObjectKeyRecordIdIndexRouteImport
      parentRoute: typeof AppOObjectKeyRecordIdRoute
    }
    '/_app/o/$objectKey/$recordId/edit': {
      id: '/_app/o/$objectKey/$recordId/edit'
      path: '/edit'
      fullPath: '/o/$objectKey/$recordId/edit'
      preLoaderRoute: typeof AppOObjectKeyRecordIdEditRouteImport
      parentRoute: typeof AppOObjectKeyRecordIdRoute
    }
  }
}

interface AppFormsFormIdRouteChildren {
  AppFormsFormIdEditRoute: typeof AppFormsFormIdEditRoute
  AppFormsFormIdIndexRoute: typeof AppFormsFormIdIndexRoute
}

const AppFormsFormIdRouteChildren: AppFormsFormIdRouteChildren = {
  AppFormsFormIdEditRoute: AppFormsFormIdEditRoute,
  AppFormsFormIdIndexRoute: AppFormsFormIdIndexRoute,
}

const AppFormsFormIdRouteWithChildren = AppFormsFormIdRoute._addFileChildren(
  AppFormsFormIdRouteChildren,
)

interface AppFormsRouteChildren {
  AppFormsFormIdRoute: typeof AppFormsFormIdRouteWithChildren
  AppFormsIndexRoute: typeof AppFormsIndexRoute
}

const AppFormsRouteChildren: AppFormsRouteChildren = {
  AppFormsFormIdRoute: AppFormsFormIdRouteWithChildren,
  AppFormsIndexRoute: AppFormsIndexRoute,
}

const AppFormsRouteWithChildren = AppFormsRoute._addFileChildren(
  AppFormsRouteChildren,
)

interface AppQuotesQuoteIdRouteChildren {
  AppQuotesQuoteIdPrintRoute: typeof AppQuotesQuoteIdPrintRoute
  AppQuotesQuoteIdIndexRoute: typeof AppQuotesQuoteIdIndexRoute
}

const AppQuotesQuoteIdRouteChildren: AppQuotesQuoteIdRouteChildren = {
  AppQuotesQuoteIdPrintRoute: AppQuotesQuoteIdPrintRoute,
  AppQuotesQuoteIdIndexRoute: AppQuotesQuoteIdIndexRoute,
}

const AppQuotesQuoteIdRouteWithChildren =
  AppQuotesQuoteIdRoute._addFileChildren(AppQuotesQuoteIdRouteChildren)

interface AppQuotesRouteChildren {
  AppQuotesQuoteIdRoute: typeof AppQuotesQuoteIdRouteWithChildren
  AppQuotesNewRoute: typeof AppQuotesNewRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
}

const AppQuotesRouteChildren: AppQuotesRouteChildren = {
  AppQuotesQuoteIdRoute: AppQuotesQuoteIdRouteWithChildren,
  AppQuotesNewRoute: AppQuotesNewRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
}

const AppQuotesRouteWithChildren = AppQuotesRoute._addFileChildren(
  AppQuotesRouteChildren,
)

interface AppSettingsObjectsRouteChildren {
  AppSettingsObjectsObjectKeyRoute: typeof AppSettingsObjectsObjectKeyRoute
  AppSettingsObjectsIndexRoute: typeof AppSettingsObjectsIndexRoute
}

const AppSettingsObjectsRouteChildren: AppSettingsObjectsRouteChildren = {
  AppSettingsObjectsObjectKeyRoute: AppSettingsObjectsObjectKeyRoute,
  AppSettingsObjectsIndexRoute: AppSettingsObjectsIndexRoute,
}

const AppSettingsObjectsRouteWithChildren =
  AppSettingsObjectsRoute._addFileChildren(AppSettingsObjectsRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsObjectsRoute: typeof AppSettingsObjectsRouteWithChildren
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsObjectsRoute: AppSettingsObjectsRouteWithChildren,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppOObjectKeyRecordIdRouteChildren {
  AppOObjectKeyRecordIdEditRoute: typeof AppOObjectKeyRecordIdEditRoute
  AppOObjectKeyRecordIdIndexRoute: typeof AppOObjectKeyRecordIdIndexRoute
}

const AppOObjectKeyRecordIdRouteChildren: AppOObjectKeyRecordIdRouteChildren = {
  AppOObjectKeyRecordIdEditRoute: AppOObjectKeyRecordIdEditRoute,
  AppOObjectKeyRecordIdIndexRoute: AppOObjectKeyRecordIdIndexRoute,
}

const AppOObjectKeyRecordIdRouteWithChildren =
  AppOObjectKeyRecordIdRoute._addFileChildren(
    AppOObjectKeyRecordIdRouteChildren,
  )

interface AppOObjectKeyRouteChildren {
  AppOObjectKeyRecordIdRoute: typeof AppOObjectKeyRecordIdRouteWithChildren
  AppOObjectKeyNewRoute: typeof AppOObjectKeyNewRoute
  AppOObjectKeyIndexRoute: typeof AppOObjectKeyIndexRoute
}

const AppOObjectKeyRouteChildren: AppOObjectKeyRouteChildren = {
  AppOObjectKeyRecordIdRoute: AppOObjectKeyRecordIdRouteWithChildren,
  AppOObjectKeyNewRoute: AppOObjectKeyNewRoute,
  AppOObjectKeyIndexRoute: AppOObjectKeyIndexRoute,
}

const AppOObjectKeyRouteWithChildren = AppOObjectKeyRoute._addFileChildren(
  AppOObjectKeyRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExamplesRoute: typeof AppExamplesRoute
  AppFormsRoute: typeof AppFormsRouteWithChildren
  AppQuotesRoute: typeof AppQuotesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTasksRoute: typeof AppTasksRoute
  AppOObjectKeyRoute: typeof AppOObjectKeyRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExamplesRoute: AppExamplesRoute,
  AppFormsRoute: AppFormsRouteWithChildren,
  AppQuotesRoute: AppQuotesRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTasksRoute: AppTasksRoute,
  AppOObjectKeyRoute: AppOObjectKeyRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
